apiVersion: v1
kind: Secret
metadata:
  name:  reciter-report-secrets
  namespace: reciter
  labels:
    app: reciter-report
    environment: dev
    tier: backend
    owner: szd2013
stringData:
  DB_USERNAME: admin
  DB_PASSWORD: <<DB_PASSWORD>>
  AWS_ACCESS_KEY_ID: <<AWS_ACCESS_KEY_ID>>
  AWS_SECRET_ACCESS_KEY: <<AWS_SECRET_ACCESS_KEY>>
